### ISSUE TITLE
Script errors "ERROR: Postprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location"

### ISSUE THREAD

**Issue by Sambouza** [ThioJoe/youtube-dl-easy#3]
Chose the first option in the ps1 script, but returns an error

The script is placed with the .exe file which was downloaded from the github page.
The whole program directory is placed under a subdirectory of C:\Users\...

![image](https://github.com/ThioJoe/youtube-dl-easy/assets/128921516/28319d59-b62e-4dba-9dfd-97f544f6a694)

**Comment by Sambouza** [comment]
Solved by downloading ffmpeg.exe 😅

**Comment by Sambouza** [comment]
# NOTE:
Although I had ffmpeg in the same directory, it still errored out.
The solution is as following:

Changing
```pwsh
$ffmpeg_location="`"ffmpeg.exe"`"
```
to
```pwsh
$ffmpeg_location="ffmpeg.exe"
```
fixes this.

**Comment by NiyaShy** [comment]
The weird triple quotation marks for ffmpeg_location and output_location (I added absolute paths for both) caused issues for me as well, and just as for you, replacing them with just normal quotation marks (" ") fixed it.
